version: '3'

services:
  backend:
    image: luna-backend:latest
    ports:
      - 8000:8000
    volumes:
      - ./backend:/backend
      - ./scripts:/scripts
    env_file:
      - ./env/dev.env
    command: "sh /scripts/dev.sh"
    depends_on:
      - postgres


  postgres:
    image: postgres:latest
    env_file:
      - ./env/dev.env
    ports:
      - 5555:5432
    volumes:
      - postgres_db:/var/lib/postgresql/data


volumes:
  postgres_db:
